apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app: app
  name: app
spec:
  project: app-project
  source:
    repoURL: https://github.com/illusionist99/malaoui_ception
    targetRevision: main
    path: p3/confs/app/
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
