apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: dev
  labels:
    app: app
spec:
  type: LoadBalancer
  ports:
  - port: 8888
    targetPort: 8888
    protocol: TCP
    name: app
  selector:
    app: app
